#ifndef maspar_h
#define maspar_h 1
//--------------------------------------------------------------------
// File maspar.h defines the interface to the parser generated by
// yacc.
//--------------------------------------------------------------------
// Author: Thomas R. Turner                                           
// E-Mail: trturner@uco.edu                                          
// Date:   October, 2015                                              
//--------------------------------------------------------------------
// Copyright October, 2015 by Thomas R. Turner
// Do not reproduce without permission from Thomas R. Turner.
//--------------------------------------------------------------------
//Application include files
//--------------------------------------------------------------------
#include "maslex.h"
//--------------------------------------------------------------------
//--------------------------------------------------------------------
//Function yyparse is the parser generated by yacc.                  
//--------------------------------------------------------------------
#ifdef __cplusplus
extern "C" 
#endif
int yyparse (void);
#endif
class Parser : public Lexer {
public:
  Parser(FILE* i):Lexer(i){}
  int Parse(void) { return yyparse(); }
};
